export const ADD_TICKET_TO_COLUMN = "ADD_TICKET_TO_COLUMN";
export const REMOVE_TICKET_FROM_COLUMN = "REMOVE_TICKET_FROM_COLUMN";
export const ADD_COLUMN = "ADD_COLUMN";
export const REMOVE_COLUMN = "REMOVE_COLUMN";
export const SET_TICKETFORMVISIBILITY = "SET_TICKETFORMVISIBILITY";
