export const ADD_TICKET_TO_COLUMN = "ADD_TICKET_TO_COLUMN";
export const REMOVE_TICKET_FROM_COLUMN = "REMOVE_TICKET_FROM_COLUMN";
export const ADD_COLUMN = "ADD_COLUMN";
export const REMOVE_COLUMN = "REMOVE_COLUMN";
export const MOVE_TICKET_TO_COLUMN = "MOVE_TICKET_TO_COLUMN";
export const REORDER_TICKET = "REORDER_TICKET";
export const REORDER_COLUMN = "REORDER_COLUMN";
