export const TICKET_COLUMN_ADD = "COLUMNTICKET_ADD";
export const TICKET_COLUMN_REMOVE = "COLUMNTICKET_REMOVE";
export const COLUMN_ADD = "COLUMN_ADD";
export const COLUMN_REMOVE = "COLUMN_REMOVE";
export const TICKET_SETFORMVISIBILITY = "TICKET_SETFORMVISIBILITY";
export const COLUMN_REORDER = "COLUMN_REODER";
export const COLUMN_MOVETICKETFROMTO = "COLUMN_MOVETICKETFROMTO";
export const TICKET_REORDER = "TICKET_REORDER";
